#define     Run_Led     P3.0
#define     Stop_Led    P3.1
#define     Set_Led     P3.2
#define     Run_Key     P3.3
#define     Stop_Key    P3.4
#define     Inc_Key     P3.7
#define     Dec_Key     P3.5

#define     On      0
#define     Off     1
#define     Run     0
#define     Stop    1

/* void delay(data unsigned char Count); */
/* void initiliaze(void); */
/* void key_scan(void); */
/* void end_led(void); */
