/*    ------------------------
           I / O   M A P
      ------------------------ */
#define         SEC             0x8000          /* Second */
#define         SEC_A           0x8001          /* Second Alarm */
#define         MIN             0x8002          /* Minutes */
#define         MIN_A           0x8003          /* Minutes Alarm */
#define         HOUR            0x8004          /* Hours */
#define         HOUR_A          0x8005          /* Hours Alarm */
#define         DAY_W           0x8006          /* Day of Week */
#define         DAY_M           0x8007          /* Day of Month */
#define         MONTH           0x8008          /* Month */
#define         YEAR            0x8009          /* Year */
#define         REGA            0x800A          /* Register A */
#define         REGB            0x800B          /* Register B */
#define         REGC            0x800C          /* Register C */
#define         REGD            0x800D          /* Register D */
